# Generated by Django 6.0.5 on 2026-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated, e.g. Django, React, PostgreSQL', max_length=300)),
                ('thumbnail', models.ImageField(upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
                ('category', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('API', 'API'), ('ML', 'Machine Learning'), ('Other', 'Other')], max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
