# Generated by Django 6.0.5 on 2026-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(default='Phnom Penh, Cambodia', max_length=100)),
                ('availability', models.CharField(choices=[('open', 'Open to Opportunities'), ('freelance', 'Freelance Only'), ('internship', 'Internship Only'), ('unavailable', 'Not Available')], default='open', max_length=20)),
                ('languages', models.CharField(default='Khmer (Native), English (Professional)', help_text='Comma-separated, e.g. Khmer (Native), English (Professional)', max_length=200)),
                ('interests', models.CharField(default='Fintech, Web Development, Open Source', help_text='Comma-separated, e.g. Fintech, Web Development', max_length=200)),
                ('contact_blurb', models.TextField(blank=True, default="I'm open to internships, freelance projects, and collaborations. If you're building something in fintech or web development and need a motivated developer, let's talk.", help_text="Paragraph shown in the 'Let's Work Together' section")),
            ],
            options={
                'verbose_name': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=80)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=50)),
                ('section', models.CharField(choices=[('coding', 'Coding'), ('it_support', 'IT Support')], default='coding', help_text='Which card this skill appears in', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
