# Generated by Django 6.0.5 on 2026-05-24 14:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='contact_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='interests',
            field=models.CharField(default='Fintech, Web Development, Open Source', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='languages',
            field=models.CharField(default='Khmer (Native), English (Professional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='section',
            field=models.CharField(choices=[('coding', 'Coding'), ('it_support', 'IT Support')], default='coding', max_length=20),
        ),
    ]
