# Generated by Django 6.0.5 on 2026-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_galleryitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='resume',
            field=models.URLField(blank=True),
        ),
    ]
