# Generated by Django 6.0.5 on 2026-05-25 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_herosection_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
