# Generated by Django 6.0.5 on 2026-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_galleryitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
