# Generated by Django 6.0.5 on 2026-05-26 08:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_herosection_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon'),
        ),
    ]
